apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: example-health-pipeline
spec:
  resources:
  - name: patientui-git
    type: git
  - name: patientui-image
    type: image
  - name: adminui-git
    type: git
  - name: adminui-image
    type: image
  - name: analytics-git
    type: git
  - name: analytics-dataservice-image
    type: image
  - name: analytics-webapp-image
    type: image
  tasks:
  - name: build-patientui
    taskRef:
      name: s2i-nodejs
    params:
      - name: TLSVERIFY
        value: "false"
      - name: PATH_CONTEXT
        value: "./site"
    resources:
      inputs:
      - name: source
        resource: patientui-git
      outputs:
      - name: image
        resource: patientui-image
  - name: build-adminui
    taskRef:
      name: s2i-php
    params:
      - name: TLSVERIFY
        value: "false"
      - name: PATH_CONTEXT
        value: "./src"
    resources:
      inputs:
      - name: source
        resource: adminui-git
      outputs:
      - name: image
        resource: adminui-image
  - name: build-analytics-dataservice
    taskRef:
      name: s2i-nodejs
    params:
      - name: TLSVERIFY
        value: "false"
      - name: PATH_CONTEXT
        value: "./data-service"
    resources:
      inputs:
      - name: source
        resource: analytics-git
      outputs:
      - name: image
        resource: analytics-dataservice-image
  - name: build-analytics-webapp
    taskRef:
      name: s2i-nodejs
    params:
      - name: TLSVERIFY
        value: "false"
      - name: PATH_CONTEXT
        value: "./web"
    env:
      - name: DATA_SERVER
        value: "http://analytics-dataservice-tekton-pipelines.olaph-iro5-5290c8c8e5797924dc1ad5d1b85b37c0-0001.us-east.containers.appdomain.cloud"
      - name: MAPBOX_ACCESS_TOKEN
        value: "pk.eyJ1IjoibWFnaWNtYXgzMiIsImEiOiJjanR0MGxubXcweHVzNDVwaWV2MGQ1ZWp3In0.8YiTJ8uuaq831eLcsjc03w"
    resources:
      inputs:
      - name: source
        resource: analytics-git
      outputs:
      - name: image
        resource: analytics-webapp-image
  - name: deploy-patientui
    taskRef:
      name: openshift-client
    runAfter:
      - build-patientui
    params:
    - name: ARGS
      value: "new-app patientui"
  - name: deploy-ol
    taskRef:
      name: openshift-client
    params:
    - name: ARGS
      value: "new-app ykoyfman/ol-example-health"
  - name: deploy-adminui
    taskRef:
      name: openshift-client
    runAfter:
      - build-adminui
    params:
    - name: ARGS
      value: "new-app adminui"
  - name: deploy-analytics-dataservice
    taskRef:
      name: openshift-client
    runAfter:
      - build-analytics-dataservice
    params:
    - name: ARGS
      value: "new-app analytics-dataservice"
  - name: deploy-analytics-webapp
    taskRef:
      name: openshift-client
    runAfter:
      - build-analytics-webapp
    params:
    - name: ARGS
      value: "new-app analytics-webapp"
  - name: expose-patientui
    taskRef:
      name: openshift-client
    runAfter:
      - deploy-patientui
    params:
    - name: ARGS
      value: "expose svc/patientui"
  - name: expose-adminui
    taskRef:
      name: openshift-client
    runAfter:
      - deploy-adminui
    params:
    - name: ARGS
      value: "expose svc/adminui"
  - name: expose-analytics-dataservice
    taskRef:
      name: openshift-client
    runAfter:
      - deploy-analytics-dataservice
    params:
    - name: ARGS
      value: "expose svc/analytics-dataservice --port=3000 --protocol=TCP"
  - name: expose-analytics-webapp
    taskRef:
      name: openshift-client
    runAfter:
      - deploy-analytics-webapp
    params:
    - name: ARGS
      value: "expose svc/analytics-webapp --port=4000 --protocol=TCP"
